import json

# Example script to generate a markdown file
data = {
    "title": "Hello, World!",
    "content": "This is a sample content generated by a Python script."
}

with open('docs/index.md', 'w') as file:
    file.write(f"# {data['title']}\n\n{data['content']}")
